export const books = [
  {
    title: "Luna of the Kingdom",
    characterName: "Luna",
    world: "Floating Kingdom",
    mood: "Magical",
    pageCount: 8,
    scene: "A lantern-lit cliff overlooking a castle in the clouds.",
    color: "#5b3d8f",
  },
  {
    title: "The Star Map",
    characterName: "Orin",
    world: "Floating Kingdom",
    mood: "Magical",
    pageCount: 6,
    scene: "A hidden tower where constellations write themselves.",
    color: "#3d4e8f",
  },
  {
    title: "Whisper Path",
    characterName: "Mira",
    world: "Whispering Woods",
    mood: "Mysterious",
    pageCount: 10,
    scene: "A forest trail that only appears at dusk.",
    color: "#2d5a4a",
  },
  {
    title: "The Quiet River",
    characterName: "Theo",
    world: "Whispering Woods",
    mood: "Mysterious",
    pageCount: 7,
    scene: "Fog over a river that hums with old songs.",
    color: "#1f4d3d",
  },
  {
    title: "Lost Lanterns",
    characterName: "Nia",
    world: "Underwater City",
    mood: "Mysterious",
    pageCount: 9,
    scene: "Glass streets glowing far below the waves.",
    color: "#24556b",
  },
  {
    title: "Candy Chaos",
    characterName: "Pip",
    world: "Candy Land",
    mood: "Funny",
    pageCount: 5,
    scene: "A marshmallow mountain that keeps sneezing sugar.",
    color: "#a14b6a",
  },
  {
    title: "The Giggle Gate",
    characterName: "Bram",
    world: "Candy Land",
    mood: "Funny",
    pageCount: 6,
    scene: "A chocolate bridge that tells terrible jokes.",
    color: "#8b4d2a",
  },
  {
    title: "Snow Ghost Peak",
    characterName: "Elsa",
    world: "Snowy Mountains",
    mood: "Spooky",
    pageCount: 8,
    scene: "A frozen door that knocks back when you knock.",
    color: "#3a3f6b",
  },
  {
    title: "The Pale Trail",
    characterName: "Kai",
    world: "Snowy Mountains",
    mood: "Spooky",
    pageCount: 7,
    scene: "Footprints in the snow that walk beside you.",
    color: "#4a3b63",
  },
];
